// <auto-generated />
using CommercialManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CommercialManagement.API.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260905093000_AddProduitPhotoUrl")]
partial class AddProduitPhotoUrl
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        ApplicationDbContextModelSnapshot.Build(modelBuilder);
    }
}
